### ISSUE TITLE
Broken pack, read for more

### ISSUE THREAD

**Issue by OverloadedWolf** [gilfort/CurseOfGaia#7]
So, here is a couple of issues:

1. On start-up, there is no questbook
2. No way to tell if there is a certain map to go with the pack
3. Get rid of useless resource packs

**Comment by gilfort** [comment]
The Questbook is not in the pack at the moment, because the last tested version was broken on servers. 
The pack is intended to go with normal generation (or about any worldgeneration you'd like to use, maybe i should print that into the description. 
If any resourcepacks are shipped automatically with the pack its indeed a mistake on my side, thanks for the info, i'll take a look into it.

**Comment by gilfort** [comment]
Edited Description and "got rid of useless resource packs"...
